### ISSUE TITLE
Uncaught Exception: TypeError: data should be a string, Buffer or Uint8Array

### ISSUE THREAD

**Issue by tdwesten** [DavideViolante/ocr-space-api-wrapper#1]
Hi there, thanks for building this wrapper! 

I got a issue with parsing the options, when i pass a boolean i got this error: 
`Uncaught Exception: TypeError: data should be a string, Buffer or Uint8Array` 

I this this is related to this question; https://stackoverflow.com/questions/63938549/axios-data-should-be-a-string-buffer-or-uint8array. 
I think you can fix this by wrapping all (or only the boolean's) in JSON.stringify(). 

Greetings!

**Comment by DavideViolante** [comment]
Hi, thanks for pointing this out, I can confirm that every param should be a String due to FormData, as you can see from the source too:
https://github.com/DavideViolante/ocr-space-api-wrapper/blob/master/index.js#L43
I assume you tried to pass a boolean for one of the options.

I will fix that converting to String any param that is passed.

**Comment by DavideViolante** [comment]
Let me know if the new version works for you now, even passing booleans in options.

**Comment by tdwesten** [comment]
@DavideViolante thanks for fixing!
