### ISSUE TITLE
Can this package work with a Blob as an input?

### ISSUE THREAD

**Issue by salohcinzero** [DavideViolante/ocr-space-api-wrapper#7]
I'm trying to send images to the api that have been uploaded by the user directly. So i dont have a remote url, a local url, or a base64 image. All i have is the image Blob.

Is this possible to do with this pkg?

**Comment by DavideViolante** [comment]
This package is a wrapper for [ocr.space API](https://ocr.space/OCRAPI), so it accept the same input as that.
I think that if you have the Blob, you have or you can generate in fact the local file, so then you can use local url because the user is actually uploading something somewhere.

Please provide me more info or the code you are using to create the Blob and I'll try to help you further.

**Comment by acc-nicholas** [comment]
I have a post on the forum, but not getting any support there:
https://forum.ui.vision/t/file-type-not-detected/6698

Nextjs Api route code:
```
import fetch from 'isomorphic-unfetch'
import { NextApiRequest, NextApiResponse } from 'next'
const { OCR_SECRET } = process.env

if (!OCR_SECRET) {
    throw new Error(
        'Please define the OCR_SECRET environment variable inside .env.local'
    )
}

export default async (req: NextApiRequest, res: NextApiResponse) => {
    if (req.method === 'POST') {
        const params: RequestInit = {
            method: 'POST',
            mode: 'cors',
            headers: {
                'Content-Type': 'multipart/form-data',
                'Access-Control-Allow-Origin': '*',
                apikey: OCR_SECRET,
            },
            body: req.body,
        }
        await fetch('https://api8.ocr.space/parse/image', params)
            .then(r => r.json())
            .then(json => res.json(json))
    }
}
```

What i learned since that forum post and asking here is that nextjs actually parses the original request body into a single string that includes the headers AND the body. That's why the above doesn't work as a body passed straight through to the ocr api.

I tried using formidable and your pkg to grab the original file as a `File` and send it along to ocr, but i wasn't able to get that working either...

**Comment by DavideViolante** [comment]
I think this is more a problem of "how to upload a file using SPA frameworks" like React, Next or Angular.
I also had some troubles using Angular but I made it work both locally and remotely using S3 or EC2 server as storage.

For Next I found these 2, maybe they can help:
- https://gist.github.com/agmm/da47a027f3d73870020a5102388dd820 BE
- https://gist.github.com/AshikNesin/e44b1950f6a24cfcd85330ffc1713513 FE

In Angular I used an input type file that calls this function:
```ts
return this.fileService.upload(event.target.file).subscribe(...)
```

```ts
upload(file: File): Observable<any> {
    const formData: FormData = new FormData();
    formData.append('file', file);
    return this.http.request(new HttpRequest('POST', '/backend/endpoint/toupload/here', formData, { responseType: 'json' }));
  }
```

and on backend I used multer https://www.npmjs.com/package/multer#diskstorage or multer-s3
